swagger: "2.0"
info:
  title: Auth APIs
  description: Các API xác thực người dùng
  version: "1.0.0"

tags:
  - name: Auth
    description: API xác thực người dùng

paths:
  /auth/signup:
    post:
      tags: [Auth]
      summary: Đăng ký tài khoản
      consumes:
        - application/json
      parameters:
        - in: body
          name: body
          description: Thông tin đăng ký
          required: true
          schema:
            $ref: "#/definitions/SignupBody"
      responses:
        201:
          description: Đăng ký thành công
          schema:
            $ref: "#/definitions/SuccessMessage"

  /auth/login:
    post:
      tags: [Auth]
      summary: Đăng nhập
      consumes:
        - application/json
      parameters:
        - in: body
          name: body
          description: Thông tin đăng nhập
          required: true
          schema:
            $ref: "#/definitions/LoginBody"
      responses:
        200:
          description: Đăng nhập thành công
          schema:
            $ref: "#/definitions/LoginSuccess"

  /auth/forgot-password:
    post:
      tags: [Auth]
      summary: Quên mật khẩu
      consumes:
        - application/json
      parameters:
        - in: body
          name: body
          schema:
            $ref: "#/definitions/ForgotPassBody"
      responses:
        200:
          description: Gửi mail thành công
          schema:
            $ref: "#/definitions/SuccessMessage"

  /auth/logout:
    post:
      tags: [Auth]
      summary: Đăng xuất
      security:
        - Bearer: []
      responses:
        200:
          description: Đăng xuất thành công
          schema:
            $ref: "#/definitions/SuccessMessage"

  /auth/refresh:
    post:
      tags: [Auth]
      summary: Làm mới token
      security:
        - Bearer: []
      responses:
        200:
          description: Cấp token mới
          schema:
            $ref: "#/definitions/RefreshToken"

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header

definitions:
  SignupBody:
    type: object
    required: [username, email, password]
    properties:
      username:
        type: string
        example: duyen123
      email:
        type: string
        example: duyen@example.com
      password:
        type: string
        example: mypassword123

  LoginBody:
    type: object
    required: [email, password]
    properties:
      email:
        type: string
        example: duyen@example.com
      password:
        type: string
        example: mypassword123

  ForgotPassBody:
    type: object
    required: [email]
    properties:
      email:
        type: string
        example: duyen@example.com

  SuccessMessage:
    type: object
    properties:
      message:
        type: string
        example: Success

  LoginSuccess:
    type: object
    properties:
      access_token:
        type: string
        example: jwt_token_here
      refresh_token:
        type: string
        example: refresh_jwt_here
      message:
        type: string
        example: Login successful

  RefreshToken:
    type: object
    properties:
      access_token:
        type: string
        example: new_access_token_here
