openapi: 3.0.0
info:
  title: Authentication API
  version: 1.0.0
  description: |
    API cho hệ thống đăng ký, đăng nhập và quản lý người dùng.
servers:
  - url: http://localhost:5000
    description: Local Server

tags:
  - name: Authentication
    description: Các API về xác thực người dùng

paths:
  /auth/signup:
    post:
      summary: Đăng ký tài khoản mới
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - email
                - password
                - confirm_password
                - birthday
              properties:
                username:
                  type: string
                  example: myduyen
                email:
                  type: string
                  example: duyen@example.com
                password:
                  type: string
                  example: 123456
                confirm_password:
                  type: string
                  example: 123456
                birthday:
                  type: string
                  format: date
                  example: 2005-10-15
      responses:
        "201":
          description: Đăng ký thành công
        "400":
          description: Dữ liệu không hợp lệ hoặc email/username đã tồn tại

  /auth/login:
    post:
      summary: Đăng nhập người dùng
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  example: duyen@example.com
                password:
                  type: string
                  example: 123456
      responses:
        "200":
          description: Đăng nhập thành công
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                  refresh_token:
                    type: string
                  user:
                    type: object
                    properties:
                      id: { type: string }
                      username: { type: string }
                      email: { type: string }
        "401":
          description: Sai email hoặc mật khẩu

  /auth/refresh:
    post:
      summary: Làm mới access token
      security:
        - bearerAuth: []
      tags:
        - Authentication
      responses:
        "200":
          description: Tạo access token mới thành công
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
        "401":
          description: Refresh token không hợp lệ hoặc hết hạn

  /auth/profile:
    get:
      summary: Lấy thông tin người dùng hiện tại
      tags:
        - Authentication
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Thông tin người dùng
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  username:
                    type: string
                  email:
                    type: string
                  birthday:
                    type: string
        "404":
          description: Không tìm thấy người dùng

  /auth/forgot-password:
    post:
      summary: Đặt lại mật khẩu
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - new_password
                - confirm_password
              properties:
                email:
                  type: string
                  example: duyen@example.com
                new_password:
                  type: string
                  example: newpass123
                confirm_password:
                  type: string
                  example: newpass123
      responses:
        "200":
          description: Đặt lại mật khẩu thành công
        "400":
          description: Mật khẩu không khớp hoặc dữ liệu thiếu
        "404":
          description: Không tìm thấy email

  /auth/logout:
    post:
      summary: Đăng xuất người dùng
      tags:
        - Authentication
      responses:
        "200":
          description: Đăng xuất thành công (client nên xóa JWT)
