openapi: 3.0.0
info:
  title: Combo API
  version: 1.0.0
  description: API

tags:
  - name: API Combo
    description: ""

paths:
  /combos:
    get:
      tags:
        - Combo
      summary: Lấy danh sách tất cả combo
      description: Trả về danh sách toàn bộ combo hiện có trong hệ thống.
      responses:
        "200":
          description: Danh sách combo trả về thành công
          content:
            application/json:
              example:
                - id: c1
                  name: Popcorn Combo
                  description: 1 bắp + 1 nước
                  price: 79000
                  image_url: https://example.com/popcorn.jpg

  /combos/{combo_id}:
    get:
      tags:
        - Combo
      summary: Lấy thông tin chi tiết combo
      description: Trả về thông tin chi tiết của combo dựa trên ID.
      parameters:
        - name: combo_id
          in: path
          required: true
          schema:
            type: string
          description: ID của combo cần lấy thông tin
      responses:
        "200":
          description: Thông tin combo trả về thành công
          content:
            application/json:
              example:
                id: c1
                name: Snack Combo
                description: 2 nước + 1 bắp
                price: 99000
                image_url: https://example.com/snack.jpg
        "404":
          description: Không tìm thấy combo
          content:
            application/json:
              example:
                message: Combo not found

  /combos/add_to_ticket:
    post:
      tags:
        - Combo
      summary: Gắn combo vào vé (User mua combo)
      description: Cho phép người dùng thêm combo đã chọn vào vé của họ.
      requestBody:
        required: true
        content:
          application/json:
            example:
              ticket_id: t123
              combo_id: c456
              quantity: 2
      responses:
        "201":
          description: Gắn combo vào vé thành công
          content:
            application/json:
              example:
                message: Combo added to ticket successfully
        "400":
          description: Thiếu thông tin ticket_id hoặc combo_id
          content:
            application/json:
              example:
                message: Missing ticket_id or combo_id
