openapi: 3.0.0
info:
  title: Room API
  version: 1.0.0
  description: API quản lý phòng chiếu phim — bao gồm các chức năng lấy danh sách, xem chi tiết, tạo mới, cập nhật và xóa phòng.

tags:
  - name: API Room
    description:

paths:
  /rooms:
    get:
      tags:
        - Room
      summary: Lấy danh sách tất cả phòng
      description: Trả về danh sách tất cả các phòng chiếu trong hệ thống.
      responses:
        "200":
          description: Danh sách phòng được trả về thành công
          content:
            application/json:
              example:
                - id: "R001"
                  cinema_id: "C001"
                  name: "Phòng 1"
                  total_seats: 100
                - id: "R002"
                  cinema_id: "C001"
                  name: "Phòng 2"
                  total_seats: 80

    post:
      tags:
        - Room
      summary: Tạo phòng chiếu mới
      description: Thêm một phòng chiếu mới vào hệ thống.
      requestBody:
        required: true
        content:
          application/json:
            example:
              cinema_id: "C001"
              name: "Phòng 3"
              total_seats: 120
      responses:
        "201":
          description: Tạo phòng chiếu mới thành công
          content:
            application/json:
              example:
                message: Room created successfully
                room_id: "R003"
        "400":
          description: Thiếu hoặc sai định dạng dữ liệu đầu vào

  /rooms/{room_id}:
    get:
      tags:
        - Room
      summary: Lấy chi tiết phòng chiếu
      description: Trả về thông tin chi tiết của một phòng chiếu theo room_id.
      parameters:
        - name: room_id
          in: path
          required: true
          schema:
            type: string
          description: ID của phòng chiếu
      responses:
        "200":
          description: Trả về chi tiết phòng thành công
          content:
            application/json:
              example:
                id: "R001"
                cinema_id: "C001"
                name: "Phòng 1"
                total_seats: 100
        "404":
          description: Không tìm thấy phòng chiếu

    put:
      tags:
        - Room
      summary: Cập nhật thông tin phòng chiếu
      description: Cập nhật tên hoặc tổng số ghế của một phòng chiếu.
      parameters:
        - name: room_id
          in: path
          required: true
          schema:
            type: string
          description: ID của phòng chiếu
      requestBody:
        required: true
        content:
          application/json:
            example:
              name: "Phòng 1 - VIP"
              total_seats: 120
      responses:
        "200":
          description: Cập nhật phòng thành công
          content:
            application/json:
              example:
                message: Room updated successfully
        "400":
          description: Dữ liệu không hợp lệ
        "404":
          description: Không tìm thấy phòng

    delete:
      tags:
        - Room
      summary: Xóa phòng chiếu
      description: Xóa một phòng chiếu ra khỏi hệ thống theo room_id.
      parameters:
        - name: room_id
          in: path
          required: true
          schema:
            type: string
          description: ID của phòng chiếu cần xóa
      responses:
        "200":
          description: Xóa phòng thành công
          content:
            application/json:
              example:
                message: Room deleted successfully
        "404":
          description: Không tìm thấy phòng chiếu
