openapi: 3.0.0
info:
  title: Seat API
  description: API quản lý ghế ngồi trong phòng chiếu.
  version: 1.0.0

paths:
  /seats:
    get:
      tags:
        - Seats
      summary: Lấy danh sách tất cả ghế
      description: Trả về danh sách toàn bộ ghế có trong hệ thống.
      responses:
        200:
          description: Danh sách ghế được trả về thành công.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Seat"

    post:
      tags:
        - Seats
      summary: Tạo ghế mới
      description: Thêm một ghế mới vào hệ thống.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - room_id
                - seat_number
                - seat_type
              properties:
                room_id:
                  type: string
                  example: "ROOM001"
                seat_number:
                  type: string
                  example: "A10"
                seat_type:
                  type: string
                  example: "VIP"
      responses:
        201:
          description: Tạo ghế mới thành công.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Seat created successfully
                  seat_id:
                    type: string
                    example: "SEAT123"
        400:
          description: Thiếu dữ liệu hoặc yêu cầu không hợp lệ.

  /seats/{seat_id}:
    get:
      tags:
        - Seats
      summary: Lấy thông tin ghế theo ID
      parameters:
        - name: seat_id
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: Trả về thông tin chi tiết của ghế.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Seat"
        404:
          description: Không tìm thấy ghế.

    put:
      tags:
        - Seats
      summary: Cập nhật thông tin ghế
      parameters:
        - name: seat_id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                seat_number:
                  type: string
                  example: "B5"
                seat_type:
                  type: string
                  example: "Standard"
      responses:
        200:
          description: Cập nhật ghế thành công.
        404:
          description: Không tìm thấy ghế.

    delete:
      tags:
        - Seats
      summary: Xóa ghế
      parameters:
        - name: seat_id
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: Xóa ghế thành công.
        404:
          description: Không tìm thấy ghế.

components:
  schemas:
    Seat:
      type: object
      properties:
        id:
          type: string
          example: "SEAT123"
        room_id:
          type: string
          example: "ROOM001"
        seat_number:
          type: string
          example: "A10"
        seat_type:
          type: string
          example: "VIP"
