openapi: 3.0.0
info:
  title: Ticket Type API
  description: API quản lý vé xem phim — bao gồm tạo, cập nhật, hủy vé và lấy thông tin chi tiết.
  version: 1.0.0
tags:
  - name: API Ticket Type
    description:

paths:
  /showtimes:
    get:
      summary: Lấy danh sách tất cả suất chiếu
      tags: [Showtime]
      responses:
        200:
          description: Danh sách suất chiếu
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      example: "st001"
                    movie_id:
                      type: string
                      example: "mv001"
                    room_id:
                      type: string
                      example: "rm001"
                    start_time:
                      type: string
                      example: "2025-10-23T19:00:00"

    post:
      summary: Tạo mới suất chiếu
      tags: [Showtime]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [movie_id, room_id, start_time]
              properties:
                movie_id:
                  type: string
                  example: "mv001"
                room_id:
                  type: string
                  example: "rm001"
                start_time:
                  type: string
                  example: "2025-10-23T19:00:00"
      responses:
        201:
          description: Tạo suất chiếu thành công
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Showtime created successfully"
                  id:
                    type: string
                    example: "st001"
        400:
          description: Thiếu dữ liệu hoặc không hợp lệ
        404:
          description: Movie hoặc Room không tồn tại

  /showtimes/{showtime_id}:
    get:
      summary: Lấy chi tiết 1 suất chiếu
      tags: [Showtime]
      parameters:
        - name: showtime_id
          in: path
          required: true
          schema:
            type: string
          description: ID của suất chiếu
      responses:
        200:
          description: Thông tin suất chiếu
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    example: "st001"
                  movie_id:
                    type: string
                    example: "mv001"
                  room_id:
                    type: string
                    example: "rm001"
                  start_time:
                    type: string
                    example: "2025-10-23T19:00:00"
        404:
          description: Showtime not found

    put:
      summary: Cập nhật suất chiếu
      tags: [Showtime]
      parameters:
        - name: showtime_id
          in: path
          required: true
          schema:
            type: string
          description: ID của suất chiếu cần cập nhật
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                movie_id:
                  type: string
                  example: "mv002"
                room_id:
                  type: string
                  example: "rm002"
                start_time:
                  type: string
                  example: "2025-10-25T20:30:00"
      responses:
        200:
          description: Cập nhật thành công
        404:
          description: Showtime, Movie hoặc Room không tồn tại

    delete:
      summary: Xóa suất chiếu
      tags: [Showtime]
      parameters:
        - name: showtime_id
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: Xóa thành công
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Showtime deleted successfully"
        404:
          description: Showtime not found

  /showtimes/{showtime_id}/available-seats:
    get:
      summary: Lấy danh sách ghế trống theo suất chiếu
      tags: [Showtime]
      parameters:
        - name: showtime_id
          in: path
          required: true
          schema:
            type: string
          description: ID của suất chiếu
      responses:
        200:
          description: Danh sách ghế trống
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      example: "seat123"
                    seat_number:
                      type: string
                      example: "A10"
                    seat_type:
                      type: string
                      example: "VIP"
                    is_available:
                      type: boolean
                      example: true
        404:
          description: Showtime not found
