openapi: 3.0.0
info:
  title: Ticket Type API
  description: API quản lý vé xem phim — bao gồm tạo, cập nhật, hủy vé và lấy thông tin chi tiết.
  version: 1.0.0
tags:
  - name: API Ticket Type
    description:

paths:
  /ticket-types:
    get:
      tags:
        - Ticket Types
      summary: Lấy tất cả loại vé
      description: Trả về danh sách tất cả các loại vé hiện có trong hệ thống.
      responses:
        200:
          description: Danh sách các loại vé
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/TicketType"
    post:
      tags:
        - Ticket Types
      summary: Tạo loại vé mới
      description: Tạo mới một loại vé trong hệ thống.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TicketTypeCreate"
      responses:
        201:
          description: Tạo loại vé thành công
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Ticket type created successfully
        400:
          description: Dữ liệu không hợp lệ

  /ticket-types/{ticket_type_id}:
    get:
      tags:
        - Ticket Types
      summary: Lấy thông tin loại vé theo ID
      parameters:
        - in: path
          name: ticket_type_id
          required: true
          schema:
            type: string
          description: ID của loại vé cần truy vấn
      responses:
        200:
          description: Thông tin loại vé
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TicketType"
        404:
          description: Không tìm thấy loại vé
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Ticket type not found

    put:
      tags:
        - Ticket Types
      summary: Cập nhật loại vé
      parameters:
        - in: path
          name: ticket_type_id
          required: true
          schema:
            type: string
          description: ID của loại vé cần cập nhật
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TicketTypeUpdate"
      responses:
        200:
          description: Cập nhật loại vé thành công
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Ticket type updated successfully
        404:
          description: Không tìm thấy loại vé

    delete:
      tags:
        - Ticket Types
      summary: Xóa loại vé
      parameters:
        - in: path
          name: ticket_type_id
          required: true
          schema:
            type: string
          description: ID của loại vé cần xóa
      responses:
        200:
          description: Xóa thành công
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Ticket type deleted successfully
        404:
          description: Không tìm thấy loại vé
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Ticket type not found

components:
  schemas:
    TicketType:
      type: object
      properties:
        id:
          type: string
          example: "d3b07384-d9a5-11ee-bb88-0242ac120002"
        name:
          type: string
          example: "Vé người lớn"
        description:
          type: string
          example: "Dành cho khách hàng trên 18 tuổi"
        base_price:
          type: number
          format: float
          example: 120000
        room_type:
          type: string
          example: "2D"

    TicketTypeCreate:
      type: object
      required:
        - name
        - base_price
        - room_type
      properties:
        name:
          type: string
          example: "Vé học sinh"
        description:
          type: string
          example: "Giảm giá cho học sinh, sinh viên"
        base_price:
          type: number
          example: 90000
        room_type:
          type: string
          example: "2D"

    TicketTypeUpdate:
      type: object
      properties:
        name:
          type: string
          example: "Vé VIP"
        description:
          type: string
          example: "Ghế VIP có dịch vụ cao cấp"
        base_price:
          type: number
          example: 180000
        room_type:
          type: string
          example: "3D"
